#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Train and evaluate a curated 23-class Risk Category classifier with Llama-3.1-8B-Instruct + QLoRA.

This script is intentionally self-contained and uses explicit curated paths by default.
It does not overwrite the previous Report 5 model or outputs.

Default inputs:
  data/risk_description_only_main_classes_curated_23class/risk_train.csv
  data/risk_description_only_main_classes_curated_23class/risk_test.csv
  data/risk_description_only_main_classes_curated_23class/risk_label_list.json

Default outputs:
  models/llama31_8b_risk_description_only_main_classes_curated_23class
  outputs/risk_category_prediction_curated_23class/evaluation
"""

import argparse
import gc
import inspect
import json
import os
import random
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import accuracy_score, classification_report, f1_score
from torch.utils.data import Dataset

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    Trainer,
    TrainingArguments,
    set_seed,
)

from peft import (
    LoraConfig,
    TaskType,
    get_peft_model,
    prepare_model_for_kbit_training,
)


DEFAULT_DATA_DIR = "data/risk_description_only_main_classes_curated_23class"
DEFAULT_MODEL_DIR = "models/llama31_8b_risk_description_only_main_classes_curated_23class"
DEFAULT_OUTPUT_DIR = "outputs/risk_category_prediction_curated_23class/evaluation"
DEFAULT_BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"

DEFAULT_TEXT_COL = "WHAT_HAPPENED_ENGLISH"
DEFAULT_LABEL_COL = "curated_risk_category"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train and evaluate curated Llama-3.1-8B QLoRA Risk Category classifier."
    )

    parser.add_argument("--data-dir", default=DEFAULT_DATA_DIR)
    parser.add_argument("--output-model-dir", default=DEFAULT_MODEL_DIR)
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--base-model", default=DEFAULT_BASE_MODEL)

    parser.add_argument("--text-col", default=DEFAULT_TEXT_COL)
    parser.add_argument("--label-col", default=DEFAULT_LABEL_COL)

    parser.add_argument("--max-length", type=int, default=768)
    parser.add_argument("--epochs", type=float, default=3.0)
    parser.add_argument("--per-device-batch-size", type=int, default=4)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=4)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--warmup-ratio", type=float, default=0.03)
    parser.add_argument("--lora-r", type=int, default=32)
    parser.add_argument("--lora-alpha", type=int, default=64)
    parser.add_argument("--lora-dropout", type=float, default=0.05)

    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--eval-batch-size", type=int, default=8)
    parser.add_argument("--max-new-tokens", type=int, default=32)

    parser.add_argument(
        "--skip-train",
        action="store_true",
        help="Skip training and only evaluate an existing adapter from --output-model-dir.",
    )
    parser.add_argument(
        "--skip-eval",
        action="store_true",
        help="Skip held-out evaluation after training.",
    )
    parser.add_argument(
        "--no-bf16",
        action="store_true",
        help="Disable bf16. By default bf16 is used on CUDA devices.",
    )

    return parser.parse_args()


def ensure_paths(args: argparse.Namespace) -> Dict[str, Path]:
    data_dir = Path(args.data_dir)
    train_csv = data_dir / "risk_train.csv"
    test_csv = data_dir / "risk_test.csv"
    label_list_json = data_dir / "risk_label_list.json"

    missing = [p for p in [data_dir, train_csv, test_csv, label_list_json] if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing required curated dataset path(s):\n"
            + "\n".join(str(p) for p in missing)
            + "\n\nExpected dataset directory was generated by 06_prepare_curated_risk_dataset.py."
        )

    output_model_dir = Path(args.output_model_dir)
    output_dir = Path(args.output_dir)
    output_model_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    return {
        "data_dir": data_dir,
        "train_csv": train_csv,
        "test_csv": test_csv,
        "label_list_json": label_list_json,
        "output_model_dir": output_model_dir,
        "output_dir": output_dir,
    }


def load_labels(label_list_json: Path) -> List[str]:
    with open(label_list_json, "r", encoding="utf-8") as f:
        labels = json.load(f)

    if isinstance(labels, dict):
        # Accept either {"labels": [...]} or {"0": "class", ...}
        if "labels" in labels and isinstance(labels["labels"], list):
            labels = labels["labels"]
        else:
            labels = [v for _, v in sorted(labels.items(), key=lambda kv: str(kv[0]))]

    labels = [str(x).strip() for x in labels if str(x).strip()]
    if len(labels) != len(set(labels)):
        raise ValueError("Duplicate labels found in risk_label_list.json.")

    return labels


def normalise_label_text(s: str) -> str:
    s = str(s).strip().lower()
    s = re.sub(r"\s+", " ", s)
    s = s.replace("–", "-").replace("—", "-")
    return s


def load_dataframe(path: Path, text_col: str, label_col: str, allowed_labels: List[str]) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = [text_col, label_col]
    missing_cols = [c for c in required if c not in df.columns]
    if missing_cols:
        raise KeyError(f"Missing required column(s) in {path}: {missing_cols}")

    df = df.copy()
    df[text_col] = df[text_col].fillna("").astype(str).str.strip()
    df[label_col] = df[label_col].fillna("").astype(str).str.strip()
    df = df[(df[text_col] != "") & (df[label_col] != "")].reset_index(drop=True)

    allowed = set(allowed_labels)
    unknown = sorted(set(df[label_col]) - allowed)
    if unknown:
        raise ValueError(
            f"{path} contains labels not present in risk_label_list.json:\n" + "\n".join(unknown)
        )

    return df


def build_user_prompt(text: str, labels: List[str]) -> str:
    label_block = "\n".join(f"- {x}" for x in labels)
    return (
        "Classify the following incident description into exactly one Risk Category.\n\n"
        "Allowed Risk Categories:\n"
        f"{label_block}\n\n"
        "Incident description:\n"
        f"{text}\n\n"
        "Return only the exact Risk Category name."
    )


def build_prompt(tokenizer, text: str, labels: List[str]) -> str:
    system_msg = (
        "You are a safety incident classification assistant. "
        "You must choose one exact Risk Category from the allowed list. "
        "Do not explain your answer."
    )
    user_msg = build_user_prompt(text, labels)

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_msg},
    ]

    if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template is not None:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )

    # Fallback for tokenizers without a chat template.
    return f"System: {system_msg}\n\nUser: {user_msg}\n\nAssistant:"


class RiskSFTDataset(Dataset):
    def __init__(
        self,
        df: pd.DataFrame,
        tokenizer,
        labels: List[str],
        text_col: str,
        label_col: str,
        max_length: int,
    ):
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.labels = labels
        self.text_col = text_col
        self.label_col = label_col
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, idx: int) -> Dict[str, List[int]]:
        row = self.df.iloc[idx]
        text = str(row[self.text_col])
        label = str(row[self.label_col]).strip()

        prompt = build_prompt(self.tokenizer, text, self.labels)
        answer = label + (self.tokenizer.eos_token or "")

        prompt_ids = self.tokenizer.encode(prompt, add_special_tokens=False)
        answer_ids = self.tokenizer.encode(answer, add_special_tokens=False)

        # Keep room for the label tokens. If the prompt is too long, truncate the prompt.
        max_prompt_len = max(1, self.max_length - len(answer_ids))
        prompt_ids = prompt_ids[:max_prompt_len]

        input_ids = prompt_ids + answer_ids
        labels = [-100] * len(prompt_ids) + answer_ids
        attention_mask = [1] * len(input_ids)

        if len(input_ids) > self.max_length:
            input_ids = input_ids[: self.max_length]
            labels = labels[: self.max_length]
            attention_mask = attention_mask[: self.max_length]

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


@dataclass
class CausalLMCollator:
    tokenizer: object

    def __call__(self, features: List[Dict[str, List[int]]]) -> Dict[str, torch.Tensor]:
        pad_id = self.tokenizer.pad_token_id
        if pad_id is None:
            pad_id = self.tokenizer.eos_token_id

        max_len = max(len(f["input_ids"]) for f in features)

        batch_input_ids = []
        batch_attention_mask = []
        batch_labels = []

        for f in features:
            pad_len = max_len - len(f["input_ids"])
            batch_input_ids.append(f["input_ids"] + [pad_id] * pad_len)
            batch_attention_mask.append(f["attention_mask"] + [0] * pad_len)
            batch_labels.append(f["labels"] + [-100] * pad_len)

        return {
            "input_ids": torch.tensor(batch_input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(batch_attention_mask, dtype=torch.long),
            "labels": torch.tensor(batch_labels, dtype=torch.long),
        }


def create_training_args(args: argparse.Namespace, paths: Dict[str, Path], use_bf16: bool) -> TrainingArguments:
    trainer_ckpt_dir = paths["output_model_dir"] / "trainer_checkpoints"
    trainer_ckpt_dir.mkdir(parents=True, exist_ok=True)

    kwargs = dict(
        output_dir=str(trainer_ckpt_dir),
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.per_device_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        warmup_ratio=args.warmup_ratio,
        logging_steps=10,
        save_strategy="epoch",
        save_total_limit=2,
        remove_unused_columns=False,
        optim="paged_adamw_8bit",
        lr_scheduler_type="cosine",
        max_grad_norm=0.3,
        report_to="none",
        seed=args.seed,
        dataloader_num_workers=2,
    )

    # Some transformers versions differ slightly in accepted arguments.
    sig = inspect.signature(TrainingArguments.__init__)
    accepted = set(sig.parameters.keys())

    if "bf16" in accepted:
        kwargs["bf16"] = use_bf16
    if "fp16" in accepted:
        kwargs["fp16"] = bool(torch.cuda.is_available() and not use_bf16)

    filtered_kwargs = {k: v for k, v in kwargs.items() if k in accepted}
    return TrainingArguments(**filtered_kwargs)


def load_tokenizer(base_model: str):
    tokenizer = AutoTokenizer.from_pretrained(base_model, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"
    return tokenizer


def load_model_for_training(args: argparse.Namespace, use_bf16: bool):
    compute_dtype = torch.bfloat16 if use_bf16 else torch.float16

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,
    )

    model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=compute_dtype,
    )

    model.config.use_cache = False
    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
    )

    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    return model


def train_model(
    args: argparse.Namespace,
    paths: Dict[str, Path],
    train_df: pd.DataFrame,
    labels: List[str],
    use_bf16: bool,
):
    tokenizer = load_tokenizer(args.base_model)
    model = load_model_for_training(args, use_bf16)

    train_dataset = RiskSFTDataset(
        df=train_df,
        tokenizer=tokenizer,
        labels=labels,
        text_col=args.text_col,
        label_col=args.label_col,
        max_length=args.max_length,
    )

    collator = CausalLMCollator(tokenizer=tokenizer)
    training_args = create_training_args(args, paths, use_bf16)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        data_collator=collator,
        processing_class=tokenizer,
    )

    start = time.time()
    trainer.train()
    runtime_sec = time.time() - start

    print(f"\nTraining completed in {runtime_sec:.2f} seconds.")
    print(f"Saving adapter and tokenizer to: {paths['output_model_dir']}")

    trainer.model.save_pretrained(paths["output_model_dir"])
    tokenizer.save_pretrained(paths["output_model_dir"])

    train_metadata = {
        "base_model": args.base_model,
        "output_model_dir": str(paths["output_model_dir"]),
        "data_dir": str(paths["data_dir"]),
        "train_rows": int(len(train_df)),
        "num_labels": int(len(labels)),
        "labels": labels,
        "text_col": args.text_col,
        "label_col": args.label_col,
        "max_length": args.max_length,
        "epochs": args.epochs,
        "per_device_batch_size": args.per_device_batch_size,
        "gradient_accumulation_steps": args.gradient_accumulation_steps,
        "learning_rate": args.learning_rate,
        "warmup_ratio": args.warmup_ratio,
        "lora_r": args.lora_r,
        "lora_alpha": args.lora_alpha,
        "lora_dropout": args.lora_dropout,
        "bf16": bool(use_bf16),
        "runtime_seconds": runtime_sec,
    }

    with open(paths["output_dir"] / "curated_training_metadata.json", "w", encoding="utf-8") as f:
        json.dump(train_metadata, f, ensure_ascii=False, indent=2)

    return model, tokenizer


def load_model_for_eval(args: argparse.Namespace, output_model_dir: Path, use_bf16: bool):
    from peft import PeftModel

    compute_dtype = torch.bfloat16 if use_bf16 else torch.float16

    tokenizer = AutoTokenizer.from_pretrained(output_model_dir, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,
    )

    base = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=compute_dtype,
    )

    model = PeftModel.from_pretrained(base, output_model_dir)
    model.eval()
    return model, tokenizer


def parse_prediction(raw_text: str, labels: List[str]) -> Tuple[Optional[str], str]:
    if raw_text is None:
        return None, "empty"

    text = str(raw_text).strip()
    text = re.sub(r"^[\s\"'`]+|[\s\"'`]+$", "", text)
    first_line = text.splitlines()[0].strip() if text else ""

    norm_to_label = {normalise_label_text(x): x for x in labels}

    # Exact match on the first line or full output.
    for candidate in [first_line, text]:
        key = normalise_label_text(candidate)
        if key in norm_to_label:
            return norm_to_label[key], "exact_match"

    # Remove common prefixes and retry.
    cleaned = re.sub(
        r"^(risk category|category|answer|prediction)\s*[:\-]\s*",
        "",
        first_line,
        flags=re.IGNORECASE,
    ).strip()
    key = normalise_label_text(cleaned)
    if key in norm_to_label:
        return norm_to_label[key], "exact_match_after_prefix_removal"

    # Containment: valid only if exactly one allowed category is present.
    text_norm = normalise_label_text(text)
    found = []
    for label in labels:
        pattern = re.escape(normalise_label_text(label))
        if re.search(pattern, text_norm):
            found.append(label)

    found = sorted(set(found))
    if len(found) == 1:
        return found[0], "contained_single_category"

    if len(found) > 1:
        return None, "multiple_categories_found"

    return None, "parse_failed"


@torch.no_grad()
def generate_predictions(
    args: argparse.Namespace,
    model,
    tokenizer,
    test_df: pd.DataFrame,
    labels: List[str],
) -> pd.DataFrame:
    rows = []
    device = model.device if hasattr(model, "device") else "cuda"

    prompts = [build_prompt(tokenizer, str(x), labels) for x in test_df[args.text_col].tolist()]
    true_labels = test_df[args.label_col].astype(str).tolist()

    for start in range(0, len(prompts), args.eval_batch_size):
        end = min(start + args.eval_batch_size, len(prompts))
        batch_prompts = prompts[start:end]

        encoded = tokenizer(
            batch_prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=args.max_length,
        )

        encoded = {k: v.to(device) for k, v in encoded.items()}

        generated = model.generate(
            **encoded,
            max_new_tokens=args.max_new_tokens,
            do_sample=False,
            temperature=None,
            top_p=None,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

        input_len = encoded["input_ids"].shape[1]
        new_tokens = generated[:, input_len:]
        raw_outputs = tokenizer.batch_decode(new_tokens, skip_special_tokens=True)

        for offset, raw in enumerate(raw_outputs):
            idx = start + offset
            pred, status = parse_prediction(raw, labels)
            rows.append(
                {
                    "row_index_in_test_file": idx,
                    args.text_col: test_df.iloc[idx][args.text_col],
                    "true_risk_category": true_labels[idx],
                    "predicted_risk_category": pred if pred is not None else "",
                    "raw_model_output": raw,
                    "parse_status": status,
                    "is_valid_prediction": pred is not None,
                    "is_correct": bool(pred == true_labels[idx]) if pred is not None else False,
                }
            )

        print(f"Evaluated {end}/{len(prompts)} records", flush=True)

    return pd.DataFrame(rows)


def save_evaluation_outputs(
    args: argparse.Namespace,
    paths: Dict[str, Path],
    pred_df: pd.DataFrame,
    labels: List[str],
    runtime_sec: float,
):
    output_dir = paths["output_dir"]
    pred_path = output_dir / "curated_test_predictions.csv"
    pred_df.to_csv(pred_path, index=False)

    y_true = pred_df["true_risk_category"].astype(str).tolist()
    y_pred_with_invalid = [
        p if str(p).strip() else "__INVALID__" for p in pred_df["predicted_risk_category"].astype(str).tolist()
    ]

    valid_mask = pred_df["is_valid_prediction"].astype(bool).to_numpy()
    invalid_count = int((~valid_mask).sum())

    accuracy_all = accuracy_score(y_true, y_pred_with_invalid)
    weighted_f1_all = f1_score(y_true, y_pred_with_invalid, labels=labels, average="weighted", zero_division=0)
    macro_f1_all = f1_score(y_true, y_pred_with_invalid, labels=labels, average="macro", zero_division=0)

    if valid_mask.sum() > 0:
        valid_true = pred_df.loc[valid_mask, "true_risk_category"].astype(str).tolist()
        valid_pred = pred_df.loc[valid_mask, "predicted_risk_category"].astype(str).tolist()
        accuracy_valid_only = accuracy_score(valid_true, valid_pred)
    else:
        accuracy_valid_only = None

    report_dict = classification_report(
        y_true,
        y_pred_with_invalid,
        labels=labels,
        output_dict=True,
        zero_division=0,
    )

    report_df = pd.DataFrame(report_dict).transpose()
    report_df.to_csv(output_dir / "curated_classification_report.csv")

    parse_status_counts = (
        pred_df["parse_status"].value_counts(dropna=False).rename_axis("parse_status").reset_index(name="count")
    )
    parse_status_counts.to_csv(output_dir / "curated_parse_status_counts.csv", index=False)

    mismatches = pred_df[pred_df["true_risk_category"] != pred_df["predicted_risk_category"]].copy()
    confusion_pairs = (
        mismatches.groupby(["true_risk_category", "predicted_risk_category"], dropna=False)
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
    )
    confusion_pairs.to_csv(output_dir / "curated_confusion_pairs.csv", index=False)

    per_class_counts = []
    for label in labels:
        subset = pred_df[pred_df["true_risk_category"] == label]
        total = len(subset)
        correct = int((subset["predicted_risk_category"] == label).sum())
        per_class_counts.append(
            {
                "risk_category": label,
                "support": total,
                "correct": correct,
                "class_accuracy": correct / total if total else None,
            }
        )
    pd.DataFrame(per_class_counts).to_csv(output_dir / "curated_per_class_accuracy.csv", index=False)

    summary = {
        "data_dir": str(paths["data_dir"]),
        "model_dir": str(paths["output_model_dir"]),
        "output_dir": str(output_dir),
        "test_rows": int(len(pred_df)),
        "num_labels": int(len(labels)),
        "labels": labels,
        "invalid_predictions": invalid_count,
        "accuracy_all_rows_invalid_counted_as_wrong": float(accuracy_all),
        "weighted_f1_all_rows": float(weighted_f1_all),
        "macro_f1_all_rows": float(macro_f1_all),
        "accuracy_valid_predictions_only": None if accuracy_valid_only is None else float(accuracy_valid_only),
        "parse_status_counts": dict(zip(parse_status_counts["parse_status"], parse_status_counts["count"].astype(int))),
        "evaluation_runtime_seconds": runtime_sec,
        "output_files": {
            "predictions": str(pred_path),
            "classification_report_csv": str(output_dir / "curated_classification_report.csv"),
            "parse_status_counts_csv": str(output_dir / "curated_parse_status_counts.csv"),
            "confusion_pairs_csv": str(output_dir / "curated_confusion_pairs.csv"),
            "per_class_accuracy_csv": str(output_dir / "curated_per_class_accuracy.csv"),
        },
    }

    with open(output_dir / "curated_evaluation_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print("\nEvaluation summary:")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def main():
    args = parse_args()
    paths = ensure_paths(args)

    random.seed(args.seed)
    np.random.seed(args.seed)
    set_seed(args.seed)

    use_bf16 = bool(torch.cuda.is_available() and not args.no_bf16)

    labels = load_labels(paths["label_list_json"])
    train_df = load_dataframe(paths["train_csv"], args.text_col, args.label_col, labels)
    test_df = load_dataframe(paths["test_csv"], args.text_col, args.label_col, labels)

    print("Curated training/evaluation setup:")
    print(json.dumps(
        {
            "base_model": args.base_model,
            "data_dir": str(paths["data_dir"]),
            "train_csv": str(paths["train_csv"]),
            "test_csv": str(paths["test_csv"]),
            "output_model_dir": str(paths["output_model_dir"]),
            "output_dir": str(paths["output_dir"]),
            "train_rows": int(len(train_df)),
            "test_rows": int(len(test_df)),
            "num_labels": int(len(labels)),
            "text_col": args.text_col,
            "label_col": args.label_col,
            "bf16": use_bf16,
            "skip_train": args.skip_train,
            "skip_eval": args.skip_eval,
        },
        ensure_ascii=False,
        indent=2,
    ))

    if not args.skip_train:
        model, tokenizer = train_model(args, paths, train_df, labels, use_bf16)
    else:
        print(f"Skipping training. Loading existing adapter from {paths['output_model_dir']}.")
        model, tokenizer = load_model_for_eval(args, paths["output_model_dir"], use_bf16)

    if args.skip_eval:
        print("Skipping evaluation as requested.")
        return

    # For stable batched generation, use left padding at evaluation time.
    tokenizer.padding_side = "left"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Switch to evaluation mode before generation.
model.eval()
if hasattr(model, "config"):
    model.config.use_cache = True

print("\nStarting held-out evaluation...")
    eval_start = time.time()
    pred_df = generate_predictions(args, model, tokenizer, test_df, labels)
    eval_runtime = time.time() - eval_start
    save_evaluation_outputs(args, paths, pred_df, labels, eval_runtime)

    # Clean up explicitly.
    del model
    del tokenizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
