#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Train and evaluate a Fall-from-height 5-class Control Category classifier
with Llama-3.1-8B-Instruct + 4-bit QLoRA.

This script is self-contained and is designed for the curated Fall-from-height
Control Category dataset generated by:
  11_prepare_fall_from_height_control_curated_dataset.py

Default inputs:
  outputs/control_category_audit/fall_from_height_control_curated_dataset/risk_fh_control_train.csv
  outputs/control_category_audit/fall_from_height_control_curated_dataset/risk_fh_control_test.csv

Default outputs:
  models/llama31_8b_fh_control_5class_<input_mode>
  outputs/control_category_prediction/fh_control_5class_<input_mode>/evaluation

Input modes:
  description_only           : WHAT_HAPPENED_ENGLISH only
  description_location       : WHAT_HAPPENED_ENGLISH + Location
  description_location_risk  : WHAT_HAPPENED_ENGLISH + Location + Risk Category context

The model is trained to return exactly one allowed Control Category name.
No person-identifying wording is used in filenames or output fields.
"""

from __future__ import annotations

import argparse
import gc
import inspect
import json
import math
import os
import random
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import accuracy_score, classification_report, f1_score
from torch.utils.data import Dataset

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    Trainer,
    TrainingArguments,
    set_seed,
)

from peft import (
    LoraConfig,
    TaskType,
    get_peft_model,
    prepare_model_for_kbit_training,
)


DEFAULT_DATA_DIR = "outputs/control_category_audit/fall_from_height_control_curated_dataset"
DEFAULT_BASE_MODEL = "meta-llama/Llama-3.1-8B-Instruct"
DEFAULT_TEXT_COL = "WHAT_HAPPENED_ENGLISH"
DEFAULT_LABEL_COL = "curated_control_category"
DEFAULT_LOCATION_COL = "Location"
DEFAULT_RISK_COL = "risk_for_control_curated"
DEFAULT_RISK_VALUE = "Fall from height"

CANONICAL_CONTROL_LABELS = [
    "Earth Bunds, Signage and Truck loader stops",
    "Structural Integrity Inspect",
    "Scaffolding and Portable Ladders",
    "Fall Prevention Systems and Rope Access",
    "Mobile Working at Heights Equipment",
]

CONTROL_ALIAS_MAP = {
    "earth bunds signage and truck loader stops": "Earth Bunds, Signage and Truck loader stops",
    "earth bunds signage truck loader stops": "Earth Bunds, Signage and Truck loader stops",
    "earth bunds": "Earth Bunds, Signage and Truck loader stops",
    "bunds signage and truck loader stops": "Earth Bunds, Signage and Truck loader stops",
    "signage and truck loader stops": "Earth Bunds, Signage and Truck loader stops",
    "truck loader stops": "Earth Bunds, Signage and Truck loader stops",
    "structural integrity inspect": "Structural Integrity Inspect",
    "structural integrity": "Structural Integrity Inspect",
    "structure integrity": "Structural Integrity Inspect",
    "structural": "Structural Integrity Inspect",
    "scaffolding and portable ladders": "Scaffolding and Portable Ladders",
    "scaffolding portable ladders": "Scaffolding and Portable Ladders",
    "scaffolding ladders": "Scaffolding and Portable Ladders",
    "portable ladders": "Scaffolding and Portable Ladders",
    "ladders": "Scaffolding and Portable Ladders",
    "fall prevention systems and rope access": "Fall Prevention Systems and Rope Access",
    "fall prevention system and rope access": "Fall Prevention Systems and Rope Access",
    "fall prevention systems rope access": "Fall Prevention Systems and Rope Access",
    "fall prevention systems and rope acces": "Fall Prevention Systems and Rope Access",
    "fall prevention and rope access": "Fall Prevention Systems and Rope Access",
    "fall prevention systems": "Fall Prevention Systems and Rope Access",
    "fall prevention": "Fall Prevention Systems and Rope Access",
    "rope access": "Fall Prevention Systems and Rope Access",
    "mobile working at heights equipment": "Mobile Working at Heights Equipment",
    "mobile working at height equipment": "Mobile Working at Heights Equipment",
    "mobile work at heights equipment": "Mobile Working at Heights Equipment",
    "mobile equipment at heights": "Mobile Working at Heights Equipment",
    "mobile elevated work platform": "Mobile Working at Heights Equipment",
    "elevated work platform": "Mobile Working at Heights Equipment",
    "ewp": "Mobile Working at Heights Equipment",
    "mewp": "Mobile Working at Heights Equipment",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train/evaluate Llama-3.1-8B QLoRA Fall-from-height Control Category classifier."
    )

    parser.add_argument("--data-dir", default=DEFAULT_DATA_DIR)
    parser.add_argument("--train-file", default=None, help="Override train CSV path.")
    parser.add_argument("--test-file", default=None, help="Override test CSV path.")
    parser.add_argument("--base-model", default=DEFAULT_BASE_MODEL)

    parser.add_argument("--text-col", default=DEFAULT_TEXT_COL)
    parser.add_argument("--label-col", default=DEFAULT_LABEL_COL)
    parser.add_argument("--location-col", default=DEFAULT_LOCATION_COL)
    parser.add_argument("--risk-col", default=DEFAULT_RISK_COL)
    parser.add_argument("--risk-value", default=DEFAULT_RISK_VALUE)

    parser.add_argument(
        "--input-mode",
        default="description_location_risk",
        choices=["description_only", "description_location", "description_location_risk"],
        help="Input fields used in the prompt.",
    )

    parser.add_argument("--output-model-dir", default=None)
    parser.add_argument("--output-dir", default=None)

    parser.add_argument("--max-length", type=int, default=768)
    parser.add_argument("--epochs", type=float, default=5.0)
    parser.add_argument("--per-device-batch-size", type=int, default=4)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=4)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--warmup-ratio", type=float, default=0.03)
    parser.add_argument("--lora-r", type=int, default=32)
    parser.add_argument("--lora-alpha", type=int, default=64)
    parser.add_argument("--lora-dropout", type=float, default=0.05)

    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--eval-batch-size", type=int, default=16)
    parser.add_argument("--max-new-tokens", type=int, default=32)

    parser.add_argument(
        "--balance-train",
        action="store_true",
        help="Oversample minority classes in the training split to match the largest class. Use only as an extra experiment.",
    )
    parser.add_argument(
        "--skip-train",
        action="store_true",
        help="Skip training and evaluate an existing adapter from --output-model-dir.",
    )
    parser.add_argument(
        "--skip-eval",
        action="store_true",
        help="Skip held-out evaluation after training.",
    )
    parser.add_argument(
        "--no-bf16",
        action="store_true",
        help="Disable bf16. By default bf16 is used on CUDA devices.",
    )

    return parser.parse_args()


def default_model_dir(input_mode: str) -> str:
    return f"models/llama31_8b_fh_control_5class_{input_mode}"


def default_output_dir(input_mode: str) -> str:
    return f"outputs/control_category_prediction/fh_control_5class_{input_mode}/evaluation"


def ensure_paths(args: argparse.Namespace) -> Dict[str, Path]:
    data_dir = Path(args.data_dir)
    train_csv = Path(args.train_file) if args.train_file else data_dir / "risk_fh_control_train.csv"
    test_csv = Path(args.test_file) if args.test_file else data_dir / "risk_fh_control_test.csv"

    missing = [p for p in [data_dir, train_csv, test_csv] if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing required Fall-from-height control dataset path(s):\n"
            + "\n".join(str(p) for p in missing)
            + "\n\nExpected dataset was generated by 11_prepare_fall_from_height_control_curated_dataset.py."
        )

    output_model_dir = Path(args.output_model_dir or default_model_dir(args.input_mode))
    output_dir = Path(args.output_dir or default_output_dir(args.input_mode))
    output_model_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    return {
        "data_dir": data_dir,
        "train_csv": train_csv,
        "test_csv": test_csv,
        "output_model_dir": output_model_dir,
        "output_dir": output_dir,
    }


def normalise_text(s: object) -> str:
    if s is None:
        return ""
    if isinstance(s, float) and math.isnan(s):
        return ""
    s = str(s).strip().lower()
    s = s.replace("&", " and ")
    s = s.replace("–", "-").replace("—", "-")
    s = re.sub(r"[\u2018\u2019\u201c\u201d]", "", s)
    s = re.sub(r"[^a-z0-9]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def canonicalize_control_label(x: object, allowed_labels: List[str]) -> Optional[str]:
    if x is None:
        return None
    if isinstance(x, float) and math.isnan(x):
        return None
    raw = str(x).strip()
    if not raw:
        return None

    for label in allowed_labels:
        if raw == label:
            return label

    norm = normalise_text(raw)
    allowed_norm = {normalise_text(label): label for label in allowed_labels}
    if norm in allowed_norm:
        return allowed_norm[norm]
    if norm in CONTROL_ALIAS_MAP and CONTROL_ALIAS_MAP[norm] in allowed_labels:
        return CONTROL_ALIAS_MAP[norm]

    return None


def infer_labels(train_df: pd.DataFrame, test_df: pd.DataFrame, label_col: str) -> List[str]:
    values = pd.concat([train_df[label_col], test_df[label_col]], axis=0).dropna().astype(str).str.strip()
    counts = values.value_counts()

    # Preserve the canonical order when possible, then append any unexpected but present labels.
    labels = [x for x in CANONICAL_CONTROL_LABELS if x in set(values)]
    for label in counts.index.tolist():
        if label not in labels:
            labels.append(label)

    if not labels:
        raise ValueError("No labels found in train/test data.")
    if len(labels) != len(set(labels)):
        raise ValueError("Duplicate labels detected after label inference.")
    return labels


def load_dataframe(path: Path, args: argparse.Namespace, allowed_labels: List[str]) -> pd.DataFrame:
    df = pd.read_csv(path, low_memory=False)
    required = [args.text_col, args.label_col]
    missing_cols = [c for c in required if c not in df.columns]
    if missing_cols:
        raise KeyError(f"Missing required column(s) in {path}: {missing_cols}")

    df = df.copy()
    df[args.text_col] = df[args.text_col].fillna("").astype(str).str.strip()
    df[args.label_col] = df[args.label_col].fillna("").astype(str).str.strip()

    if args.location_col not in df.columns:
        df[args.location_col] = ""
    if args.risk_col not in df.columns:
        df[args.risk_col] = args.risk_value

    df[args.location_col] = df[args.location_col].fillna("").astype(str).str.strip()
    df[args.risk_col] = df[args.risk_col].fillna(args.risk_value).astype(str).str.strip()

    df = df[(df[args.text_col] != "") & (df[args.label_col] != "")].reset_index(drop=True)

    # Canonicalize labels to avoid harmless spelling/case variation.
    mapped = []
    unmapped = []
    for val in df[args.label_col].tolist():
        label = canonicalize_control_label(val, allowed_labels)
        if label is None:
            unmapped.append(val)
            mapped.append(val)
        else:
            mapped.append(label)
    df[args.label_col] = mapped

    unknown = sorted(set(df[args.label_col]) - set(allowed_labels))
    if unknown:
        raise ValueError(f"{path} contains labels not in allowed label set:\n" + "\n".join(unknown))

    return df


def maybe_balance_train_df(df: pd.DataFrame, label_col: str, seed: int) -> pd.DataFrame:
    counts = df[label_col].value_counts()
    if counts.empty:
        return df
    max_count = int(counts.max())
    parts = []
    for label, group in df.groupby(label_col):
        if len(group) < max_count:
            group_bal = group.sample(n=max_count, replace=True, random_state=seed)
        else:
            group_bal = group.copy()
        parts.append(group_bal)
    out = pd.concat(parts, axis=0).sample(frac=1.0, random_state=seed).reset_index(drop=True)
    return out


def build_input_text(row: pd.Series, args: argparse.Namespace) -> str:
    desc = str(row.get(args.text_col, "")).strip()
    loc = str(row.get(args.location_col, "")).strip()
    risk = str(row.get(args.risk_col, args.risk_value)).strip() or args.risk_value

    if not loc or loc.lower() in {"nan", "none", "null", "unknown", "n/a", "na"}:
        loc = "Unknown"

    if args.input_mode == "description_only":
        return f"Incident Description: {desc}"

    if args.input_mode == "description_location":
        return f"Location: {loc}\nIncident Description: {desc}"

    return f"Risk Category: {risk}\nLocation: {loc}\nIncident Description: {desc}"


def build_user_prompt(row: pd.Series, labels: List[str], args: argparse.Namespace) -> str:
    label_block = "\n".join(f"- {x}" for x in labels)
    input_text = build_input_text(row, args)
    return (
        "Classify the failed Control Category for this incident.\n\n"
        "Allowed Control Categories:\n"
        f"{label_block}\n\n"
        f"{input_text}\n\n"
        "Return only the exact Control Category name."
    )


def build_prompt(tokenizer, row: pd.Series, labels: List[str], args: argparse.Namespace) -> str:
    system_msg = (
        "You are a safety incident classification assistant. "
        "You must choose one exact Control Category from the allowed list. "
        "Do not explain your answer."
    )
    user_msg = build_user_prompt(row, labels, args)

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_msg},
    ]

    if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template is not None:
        return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    return f"System: {system_msg}\n\nUser: {user_msg}\n\nAssistant:"


class ControlSFTDataset(Dataset):
    def __init__(
        self,
        df: pd.DataFrame,
        tokenizer,
        labels: List[str],
        args: argparse.Namespace,
    ):
        self.df = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.labels = labels
        self.args = args

    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, idx: int) -> Dict[str, List[int]]:
        row = self.df.iloc[idx]
        label = str(row[self.args.label_col]).strip()

        prompt = build_prompt(self.tokenizer, row, self.labels, self.args)
        answer = label + (self.tokenizer.eos_token or "")

        prompt_ids = self.tokenizer.encode(prompt, add_special_tokens=False)
        answer_ids = self.tokenizer.encode(answer, add_special_tokens=False)

        max_prompt_len = max(1, self.args.max_length - len(answer_ids))
        prompt_ids = prompt_ids[:max_prompt_len]

        input_ids = prompt_ids + answer_ids
        labels = [-100] * len(prompt_ids) + answer_ids
        attention_mask = [1] * len(input_ids)

        if len(input_ids) > self.args.max_length:
            input_ids = input_ids[: self.args.max_length]
            labels = labels[: self.args.max_length]
            attention_mask = attention_mask[: self.args.max_length]

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }


@dataclass
class CausalLMCollator:
    tokenizer: object

    def __call__(self, features: List[Dict[str, List[int]]]) -> Dict[str, torch.Tensor]:
        pad_id = self.tokenizer.pad_token_id
        if pad_id is None:
            pad_id = self.tokenizer.eos_token_id

        max_len = max(len(f["input_ids"]) for f in features)
        batch_input_ids, batch_attention_mask, batch_labels = [], [], []

        for f in features:
            pad_len = max_len - len(f["input_ids"])
            batch_input_ids.append(f["input_ids"] + [pad_id] * pad_len)
            batch_attention_mask.append(f["attention_mask"] + [0] * pad_len)
            batch_labels.append(f["labels"] + [-100] * pad_len)

        return {
            "input_ids": torch.tensor(batch_input_ids, dtype=torch.long),
            "attention_mask": torch.tensor(batch_attention_mask, dtype=torch.long),
            "labels": torch.tensor(batch_labels, dtype=torch.long),
        }


def create_training_args(args: argparse.Namespace, paths: Dict[str, Path], use_bf16: bool) -> TrainingArguments:
    trainer_ckpt_dir = paths["output_model_dir"] / "trainer_checkpoints"
    trainer_ckpt_dir.mkdir(parents=True, exist_ok=True)

    kwargs = dict(
        output_dir=str(trainer_ckpt_dir),
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.per_device_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        warmup_ratio=args.warmup_ratio,
        logging_steps=5,
        save_strategy="epoch",
        save_total_limit=2,
        remove_unused_columns=False,
        optim="paged_adamw_8bit",
        lr_scheduler_type="cosine",
        max_grad_norm=0.3,
        report_to="none",
        seed=args.seed,
        dataloader_num_workers=2,
    )

    sig = inspect.signature(TrainingArguments.__init__)
    accepted = set(sig.parameters.keys())
    if "bf16" in accepted:
        kwargs["bf16"] = bool(use_bf16)
    if "fp16" in accepted:
        kwargs["fp16"] = bool(torch.cuda.is_available() and not use_bf16)

    return TrainingArguments(**{k: v for k, v in kwargs.items() if k in accepted})


def load_tokenizer(base_model_or_adapter: str):
    tokenizer = AutoTokenizer.from_pretrained(base_model_or_adapter, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"
    return tokenizer


def load_model_for_training(args: argparse.Namespace, use_bf16: bool):
    compute_dtype = torch.bfloat16 if use_bf16 else torch.float16

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,
    )

    model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=compute_dtype,
    )

    model.config.use_cache = False
    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
    )

    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    return model


def make_trainer(model, training_args, train_dataset, collator, tokenizer) -> Trainer:
    kwargs = dict(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        data_collator=collator,
    )
    trainer_params = set(inspect.signature(Trainer.__init__).parameters.keys())
    if "processing_class" in trainer_params:
        kwargs["processing_class"] = tokenizer
    elif "tokenizer" in trainer_params:
        kwargs["tokenizer"] = tokenizer
    return Trainer(**kwargs)


def train_model(
    args: argparse.Namespace,
    paths: Dict[str, Path],
    train_df: pd.DataFrame,
    labels: List[str],
    use_bf16: bool,
):
    tokenizer = load_tokenizer(args.base_model)
    model = load_model_for_training(args, use_bf16)

    train_dataset = ControlSFTDataset(df=train_df, tokenizer=tokenizer, labels=labels, args=args)
    collator = CausalLMCollator(tokenizer=tokenizer)
    training_args = create_training_args(args, paths, use_bf16)

    trainer = make_trainer(model, training_args, train_dataset, collator, tokenizer)

    start = time.time()
    trainer.train()
    runtime_sec = time.time() - start

    print(f"\nTraining completed in {runtime_sec:.2f} seconds.")
    print(f"Saving adapter and tokenizer to: {paths['output_model_dir']}")

    trainer.model.save_pretrained(paths["output_model_dir"])
    tokenizer.save_pretrained(paths["output_model_dir"])

    train_metadata = {
        "task": "fall_from_height_control_5class",
        "base_model": args.base_model,
        "output_model_dir": str(paths["output_model_dir"]),
        "data_dir": str(paths["data_dir"]),
        "train_rows": int(len(train_df)),
        "num_labels": int(len(labels)),
        "labels": labels,
        "text_col": args.text_col,
        "location_col": args.location_col,
        "risk_col": args.risk_col,
        "label_col": args.label_col,
        "input_mode": args.input_mode,
        "balance_train": bool(args.balance_train),
        "max_length": args.max_length,
        "epochs": args.epochs,
        "per_device_batch_size": args.per_device_batch_size,
        "gradient_accumulation_steps": args.gradient_accumulation_steps,
        "learning_rate": args.learning_rate,
        "warmup_ratio": args.warmup_ratio,
        "lora_r": args.lora_r,
        "lora_alpha": args.lora_alpha,
        "lora_dropout": args.lora_dropout,
        "bf16": bool(use_bf16),
        "runtime_seconds": runtime_sec,
    }

    with open(paths["output_dir"] / "fh_control_training_metadata.json", "w", encoding="utf-8") as f:
        json.dump(train_metadata, f, ensure_ascii=False, indent=2)

    return model, tokenizer


def load_model_for_eval(args: argparse.Namespace, output_model_dir: Path, use_bf16: bool):
    from peft import PeftModel

    compute_dtype = torch.bfloat16 if use_bf16 else torch.float16

    tokenizer = AutoTokenizer.from_pretrained(output_model_dir, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "left"

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=True,
    )

    base = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=compute_dtype,
    )

    model = PeftModel.from_pretrained(base, output_model_dir)
    model.eval()
    if hasattr(model, "config"):
        model.config.use_cache = True
    return model, tokenizer


def parse_prediction(raw_text: str, labels: List[str]) -> Tuple[Optional[str], str]:
    if raw_text is None:
        return None, "empty"

    text = str(raw_text).strip()
    text = re.sub(r"^[\s\"'`]+|[\s\"'`]+$", "", text)
    first_line = text.splitlines()[0].strip() if text else ""

    norm_to_label = {normalise_text(x): x for x in labels}

    for candidate in [first_line, text]:
        key = normalise_text(candidate)
        if key in norm_to_label:
            return norm_to_label[key], "exact_match"
        if key in CONTROL_ALIAS_MAP and CONTROL_ALIAS_MAP[key] in labels:
            return CONTROL_ALIAS_MAP[key], "alias_match"

    cleaned = re.sub(
        r"^(control category|category|answer|prediction|failed control)\s*[:\-]\s*",
        "",
        first_line,
        flags=re.IGNORECASE,
    ).strip()
    key = normalise_text(cleaned)
    if key in norm_to_label:
        return norm_to_label[key], "exact_match_after_prefix_removal"
    if key in CONTROL_ALIAS_MAP and CONTROL_ALIAS_MAP[key] in labels:
        return CONTROL_ALIAS_MAP[key], "alias_match_after_prefix_removal"

    text_norm = normalise_text(text)
    found = []
    for label in labels:
        label_norm = normalise_text(label)
        if re.search(re.escape(label_norm), text_norm):
            found.append(label)

    # Allow alias containment only if exact label containment failed.
    if not found:
        for alias_norm, label in CONTROL_ALIAS_MAP.items():
            if label in labels and re.search(re.escape(alias_norm), text_norm):
                found.append(label)

    found = sorted(set(found))
    if len(found) == 1:
        return found[0], "contained_single_category"
    if len(found) > 1:
        return None, "multiple_categories_found"

    return None, "parse_failed"


@torch.no_grad()
def generate_predictions(
    args: argparse.Namespace,
    model,
    tokenizer,
    test_df: pd.DataFrame,
    labels: List[str],
) -> pd.DataFrame:
    rows = []
    device = model.device if hasattr(model, "device") else "cuda"

    prompts = [build_prompt(tokenizer, row, labels, args) for _, row in test_df.iterrows()]
    true_labels = test_df[args.label_col].astype(str).tolist()

    for start in range(0, len(prompts), args.eval_batch_size):
        end = min(start + args.eval_batch_size, len(prompts))
        batch_prompts = prompts[start:end]

        encoded = tokenizer(
            batch_prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=args.max_length,
        )
        encoded = {k: v.to(device) for k, v in encoded.items()}

        generated = model.generate(
            **encoded,
            max_new_tokens=args.max_new_tokens,
            do_sample=False,
            temperature=None,
            top_p=None,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

        input_len = encoded["input_ids"].shape[1]
        new_tokens = generated[:, input_len:]
        raw_outputs = tokenizer.batch_decode(new_tokens, skip_special_tokens=True)

        for offset, raw in enumerate(raw_outputs):
            idx = start + offset
            row = test_df.iloc[idx]
            pred, status = parse_prediction(raw, labels)
            rows.append(
                {
                    "row_index_in_test_file": idx,
                    args.text_col: row.get(args.text_col, ""),
                    args.location_col: row.get(args.location_col, ""),
                    args.risk_col: row.get(args.risk_col, args.risk_value),
                    "input_mode": args.input_mode,
                    "true_control_category": true_labels[idx],
                    "predicted_control_category": pred if pred is not None else "",
                    "raw_model_output": raw,
                    "parse_status": status,
                    "is_valid_prediction": pred is not None,
                    "is_correct": bool(pred == true_labels[idx]) if pred is not None else False,
                }
            )

        print(f"Evaluated {end}/{len(prompts)} records", flush=True)

    return pd.DataFrame(rows)


def save_evaluation_outputs(
    args: argparse.Namespace,
    paths: Dict[str, Path],
    pred_df: pd.DataFrame,
    labels: List[str],
    runtime_sec: float,
):
    output_dir = paths["output_dir"]
    pred_path = output_dir / "fh_control_test_predictions.csv"
    pred_df.to_csv(pred_path, index=False)

    y_true = pred_df["true_control_category"].astype(str).tolist()
    y_pred_with_invalid = [
        p if str(p).strip() else "__INVALID__" for p in pred_df["predicted_control_category"].astype(str).tolist()
    ]

    valid_mask = pred_df["is_valid_prediction"].astype(bool).to_numpy()
    invalid_count = int((~valid_mask).sum())

    accuracy_all = accuracy_score(y_true, y_pred_with_invalid)
    weighted_f1_all = f1_score(y_true, y_pred_with_invalid, labels=labels, average="weighted", zero_division=0)
    macro_f1_all = f1_score(y_true, y_pred_with_invalid, labels=labels, average="macro", zero_division=0)

    if valid_mask.sum() > 0:
        valid_true = pred_df.loc[valid_mask, "true_control_category"].astype(str).tolist()
        valid_pred = pred_df.loc[valid_mask, "predicted_control_category"].astype(str).tolist()
        accuracy_valid_only = accuracy_score(valid_true, valid_pred)
    else:
        accuracy_valid_only = None

    report_dict = classification_report(
        y_true,
        y_pred_with_invalid,
        labels=labels,
        output_dict=True,
        zero_division=0,
    )
    report_df = pd.DataFrame(report_dict).transpose()
    report_df.to_csv(output_dir / "fh_control_classification_report.csv")

    parse_status_counts = (
        pred_df["parse_status"].value_counts(dropna=False).rename_axis("parse_status").reset_index(name="count")
    )
    parse_status_counts.to_csv(output_dir / "fh_control_parse_status_counts.csv", index=False)

    mismatches = pred_df[pred_df["true_control_category"] != pred_df["predicted_control_category"]].copy()
    confusion_pairs = (
        mismatches.groupby(["true_control_category", "predicted_control_category"], dropna=False)
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
    )
    confusion_pairs.to_csv(output_dir / "fh_control_confusion_pairs.csv", index=False)

    per_class_counts = []
    for label in labels:
        subset = pred_df[pred_df["true_control_category"] == label]
        total = len(subset)
        correct = int((subset["predicted_control_category"] == label).sum())
        per_class_counts.append(
            {
                "control_category": label,
                "support": total,
                "correct": correct,
                "class_accuracy": correct / total if total else None,
            }
        )
    pd.DataFrame(per_class_counts).to_csv(output_dir / "fh_control_per_class_accuracy.csv", index=False)

    summary = {
        "task": "fall_from_height_control_5class",
        "data_dir": str(paths["data_dir"]),
        "model_dir": str(paths["output_model_dir"]),
        "output_dir": str(output_dir),
        "input_mode": args.input_mode,
        "test_rows": int(len(pred_df)),
        "num_labels": int(len(labels)),
        "labels": labels,
        "invalid_predictions": invalid_count,
        "accuracy_all_rows_invalid_counted_as_wrong": float(accuracy_all),
        "weighted_f1_all_rows": float(weighted_f1_all),
        "macro_f1_all_rows": float(macro_f1_all),
        "accuracy_valid_predictions_only": None if accuracy_valid_only is None else float(accuracy_valid_only),
        "parse_status_counts": dict(zip(parse_status_counts["parse_status"], parse_status_counts["count"].astype(int))),
        "evaluation_runtime_seconds": runtime_sec,
        "output_files": {
            "predictions": str(pred_path),
            "classification_report_csv": str(output_dir / "fh_control_classification_report.csv"),
            "parse_status_counts_csv": str(output_dir / "fh_control_parse_status_counts.csv"),
            "confusion_pairs_csv": str(output_dir / "fh_control_confusion_pairs.csv"),
            "per_class_accuracy_csv": str(output_dir / "fh_control_per_class_accuracy.csv"),
        },
    }

    with open(output_dir / "fh_control_evaluation_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print("\nEvaluation summary:")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def save_label_info(paths: Dict[str, Path], labels: List[str], train_df: pd.DataFrame, test_df: pd.DataFrame, args: argparse.Namespace):
    info = {
        "labels": labels,
        "num_labels": len(labels),
        "train_distribution": train_df[args.label_col].value_counts().to_dict(),
        "test_distribution": test_df[args.label_col].value_counts().to_dict(),
    }
    with open(paths["output_dir"] / "fh_control_label_info.json", "w", encoding="utf-8") as f:
        json.dump(info, f, ensure_ascii=False, indent=2)


def main() -> None:
    args = parse_args()
    paths = ensure_paths(args)

    random.seed(args.seed)
    np.random.seed(args.seed)
    set_seed(args.seed)

    use_bf16 = bool(torch.cuda.is_available() and not args.no_bf16)

    # Read raw first to infer labels.
    raw_train = pd.read_csv(paths["train_csv"], low_memory=False)
    raw_test = pd.read_csv(paths["test_csv"], low_memory=False)
    if args.label_col not in raw_train.columns or args.label_col not in raw_test.columns:
        raise KeyError(f"Label column '{args.label_col}' must exist in both train and test files.")
    labels = infer_labels(raw_train, raw_test, args.label_col)

    train_df = load_dataframe(paths["train_csv"], args, labels)
    test_df = load_dataframe(paths["test_csv"], args, labels)

    if args.balance_train:
        original_rows = len(train_df)
        train_df = maybe_balance_train_df(train_df, args.label_col, args.seed)
        print(f"Balanced training data: {original_rows} -> {len(train_df)} rows")

    save_label_info(paths, labels, train_df, test_df, args)

    print("Fall-from-height Control Category training/evaluation setup:")
    print(json.dumps(
        {
            "base_model": args.base_model,
            "data_dir": str(paths["data_dir"]),
            "train_csv": str(paths["train_csv"]),
            "test_csv": str(paths["test_csv"]),
            "output_model_dir": str(paths["output_model_dir"]),
            "output_dir": str(paths["output_dir"]),
            "train_rows": int(len(train_df)),
            "test_rows": int(len(test_df)),
            "num_labels": int(len(labels)),
            "labels": labels,
            "text_col": args.text_col,
            "location_col": args.location_col,
            "risk_col": args.risk_col,
            "label_col": args.label_col,
            "input_mode": args.input_mode,
            "balance_train": bool(args.balance_train),
            "bf16": use_bf16,
            "skip_train": args.skip_train,
            "skip_eval": args.skip_eval,
        },
        ensure_ascii=False,
        indent=2,
    ))

    if not args.skip_train:
        model, tokenizer = train_model(args, paths, train_df, labels, use_bf16)
    else:
        print(f"Skipping training. Loading existing adapter from {paths['output_model_dir']}.")
        model, tokenizer = load_model_for_eval(args, paths["output_model_dir"], use_bf16)

    if args.skip_eval:
        print("Skipping evaluation as requested.")
        return

    tokenizer.padding_side = "left"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model.eval()
    if hasattr(model, "config"):
        model.config.use_cache = True

    print("\nStarting held-out evaluation...")
    eval_start = time.time()
    pred_df = generate_predictions(args, model, tokenizer, test_df, labels)
    eval_runtime = time.time() - eval_start
    save_evaluation_outputs(args, paths, pred_df, labels, eval_runtime)

    del model
    del tokenizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
